[package]
name = "discord_query_language"
version = "0.1.0"
edition = "2021"

[dependencies]
nom = "7.1.3"

serde = { version = "1", features = ["derive"] }
serde_json = "1"

thiserror = "1.0.63"

[dev-dependencies]
rstest = "0.22.0"